FROM rust:latest

WORKDIR /
RUN apt-get update && apt-get install kcov --no-confirm && apt-get clean --no-confirm
RUN USER=rust cargo new rust-ipv8 --lib
WORKDIR /rust-ipv8
COPY Cargo.* ./
RUN cargo build && rm ./target/debug/libipv8* && rm -rf ./src/lib.rs
